-- 코드를 작성해주세요
SELECT DISTINCT IT.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_TREE AS IT
JOIN ITEM_INFO AS II ON IT.ITEM_ID = II.ITEM_ID
WHERE PARENT_ITEM_ID IN (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = 'RARE') AND 1 IS NOT NULL
ORDER BY 1 DESC;