-- 코드를 작성해주세요
# 부모 개체와 자식 개체를 나타낼 테이블 2개를 가져오기
# 비트 연산 AND 사용 -> &
SELECT A.ID, A.GENOTYPE, B.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA AS A, ECOLI_DATA AS B
WHERE A.PARENT_ID = B.ID AND (A.GENOTYPE & B.GENOTYPE) = B.GENOTYPE
ORDER BY A.ID;