-- 코드를 작성해주세요
SELECT YEAR, LEN - ED.SIZE_OF_COLONY AS YEAR_DEV, ID
FROM ECOLI_DATA AS ED
JOIN (SELECT 
      YEAR(DIFFERENTIATION_DATE) AS YEAR, 
      MAX(SIZE_OF_COLONY) AS LEN
      FROM ECOLI_DATA
      GROUP BY 1) AS L ON YEAR(DIFFERENTIATION_DATE) = YEAR
ORDER BY 1, 2;