-- 코드를 작성해주세요
# 각 년도의 최대 값을 찾는 서브 쿼리 생성
# 년도별로 편차 구하기
# YEAR -> DATE형에서 년도만 추출
# 칼럼명은 YEAR, YEAR_DEV, ID
# 정렬은 YEAR, YEAR_DEV순
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, (MAKE_MAX.MAX_COLONY - SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM ECOLI_DATA, 
(SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_COLONY 
 FROM ECOLI_DATA 
 GROUP BY YEAR(DIFFERENTIATION_DATE)) AS MAKE_MAX
WHERE MAKE_MAX.YEAR = YEAR(DIFFERENTIATION_DATE)
ORDER BY YEAR, YEAR_DEV;