-- 코드를 작성해주세요
# 두 개의 테이블 조인 (기준 = FISH_TYPE)
# 그 중에 원하는 종 (배스와 스내퍼)만을 고른 후 갯수를 셈
# 칼럼명은 FISH_COUNT로 고정

SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO
JOIN FISH_NAME_INFO ON FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
WHERE FISH_NAME_INFO.FISH_NAME = 'BASS' OR FISH_NAME_INFO.FISH_NAME = 'SNAPPER';