-- 코드를 작성해주세요
SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM FISH_INFO AS I
JOIN FISH_NAME_INFO AS N ON I.FISH_TYPE = N.FISH_TYPE
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) AS MAX_FISH ON I.FISH_TYPE = MAX_FISH.FISH_TYPE AND I.LENGTH = MAX_FISH.MAX_LENGTH
ORDER BY I.ID;
