-- 코드를 작성해주세요
SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO AS A
JOIN FISH_NAME_INFO ON A.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
WHERE LENGTH = (SELECT MAX(LENGTH) FROM FISH_INFO WHERE FISH_TYPE = A.FISH_TYPE GROUP BY FISH_TYPE)
ORDER BY ID;