-- 코드를 작성해주세요
# 평균 길이가 33이상인 물고기들을 종류별로 -> ID대로 GROUP BY
# 10cm 이하일 경우 -> 10cm로 분류
# 고기 종류에 대해 오름차순 정렬
# 칼럼명 FISH_TYPE, FISH_COUNT, MAX_LENGTH

SELECT COUNT(*) AS FISH_COUNT, MAX(A.LENGTH) AS MAX_LENGTH, A.FISH_TYPE
FROM FISH_INFO
JOIN (SELECT ifnull(LENGTH, 10) AS LENGTH, FISH_TYPE, ID FROM FISH_INFO) AS A ON A.ID = FISH_INFO.ID
GROUP BY A.FISH_TYPE
HAVING AVG(A.LENGTH) >= 33
ORDER BY A.FISH_TYPE;